--Identity Column – BY DEFAULT
--------------------------------------------

CREATE TABLE customer 
(
    customer_id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT,
    email TEXT
);
-- TEXT olarak tanımlamayın text yüksek string veriyi tutar ve burda like ile arama yapıldıgında hata verir


-- Importing existing customers with their original IDs
INSERT INTO customer (customer_id, full_name, email)
VALUES 
(101, 'Michael', 'michael@example.com'),
(102, 'Jon', 'jon@example.com');

-- New customer with auto-generated ID
INSERT INTO customer (full_name, email)
VALUES ('Brad', 'brad@example.com');