--Identity Column – Sequence
--------------------------------------------

CREATE TABLE cars 
(
    car_id INT GENERATED BY DEFAULT AS IDENTITY
        (START WITH 10 INCREMENT BY 10),
    car_name VARCHAR NOT NULL
);

INSERT INTO cars(car_name)
VALUES
    ('Ford'),
    ('Hyundai'),
    ('Kia');
